import '../app/ui/global.css';
import { AppStateKeeper } from './context';
import {MyAppBar} from './lib/components/appbar';
import { SessionProviderWrapper } from './session_provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <AppStateKeeper>
            <SessionProviderWrapper>
              <MyAppBar></MyAppBar>
              {children}
            </SessionProviderWrapper>
          </AppStateKeeper>
      </body>
    </html>
  )
}
