import '../app/ui/global.css';
import { AppStateKeeper } from './context';
import {MyAppBar} from './appbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <AppStateKeeper>
            <MyAppBar></MyAppBar>
            {children}
          </AppStateKeeper>
      </body>
    </html>
  )
}
