import '../app/ui/global.css';
import '../app/ui/theme.css';
import { AppStateKeeper } from './lib/components/app_context';
import {MyAppBar} from './lib/components/basic_elements/appbar';
import { SessionProviderWrapper } from './lib/components/session_provider';
import { Footer } from './lib/components/basic_elements/footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <AppStateKeeper>
              <div className='app'>
                <MyAppBar></MyAppBar>
                <div className='page-body'>
                  {children}
                </div>
                <Footer></Footer>
              </div>
          </AppStateKeeper>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
